import type { Metadata } from "next";
import "./globals.css";
import ApolloProviderWrapper from "@/components/ApolloProvider";
import { Toaster } from "sonner";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return ( 
   
    <html lang="en">
   
      <body className="min-h-screen flex">
      <ApolloProviderWrapper>{children}
        <Toaster position="bottom-center"/>
      </ApolloProviderWrapper>
      </body>
      
    </html>
   
  );
}
